/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/guide/': RouteRecordInfo<'/guide/', '/guide', Record<never, never>, Record<never, never>>,
    '/guide/config/': RouteRecordInfo<'/guide/config/', '/guide/config', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/deploy': RouteRecordInfo<'/guide/getting-started/deploy', '/guide/getting-started/deploy', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/installation': RouteRecordInfo<'/guide/getting-started/installation', '/guide/getting-started/installation', Record<never, never>, Record<never, never>>,
    '/guide/getting-started/update': RouteRecordInfo<'/guide/getting-started/update', '/guide/getting-started/update', Record<never, never>, Record<never, never>>,
    '/guide/writing/asset-handling': RouteRecordInfo<'/guide/writing/asset-handling', '/guide/writing/asset-handling', Record<never, never>, Record<never, never>>,
    '/guide/writing/frontmatter': RouteRecordInfo<'/guide/writing/frontmatter', '/guide/writing/frontmatter', Record<never, never>, Record<never, never>>,
    '/guide/writing/i18n': RouteRecordInfo<'/guide/writing/i18n', '/guide/writing/i18n', Record<never, never>, Record<never, never>>,
    '/guide/writing/markdown': RouteRecordInfo<'/guide/writing/markdown', '/guide/writing/markdown', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/notes/': RouteRecordInfo<'/notes/', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/reference/': RouteRecordInfo<'/reference/', '/reference', Record<never, never>, Record<never, never>>,
    '/reference/frontmatter-config/': RouteRecordInfo<'/reference/frontmatter-config/', '/reference/frontmatter-config', Record<never, never>, Record<never, never>>,
    '/reference/frontmatter-config/features': RouteRecordInfo<'/reference/frontmatter-config/features', '/reference/frontmatter-config/features', Record<never, never>, Record<never, never>>,
    '/reference/frontmatter-config/home-page': RouteRecordInfo<'/reference/frontmatter-config/home-page', '/reference/frontmatter-config/home-page', Record<never, never>, Record<never, never>>,
    '/reference/site-config': RouteRecordInfo<'/reference/site-config', '/reference/site-config', Record<never, never>, Record<never, never>>,
    '/reference/theme-config/': RouteRecordInfo<'/reference/theme-config/', '/reference/theme-config', Record<never, never>, Record<never, never>>,
    '/reference/theme-config/footer': RouteRecordInfo<'/reference/theme-config/footer', '/reference/theme-config/footer', Record<never, never>, Record<never, never>>,
    '/reference/theme-config/home-page': RouteRecordInfo<'/reference/theme-config/home-page', '/reference/theme-config/home-page', Record<never, never>, Record<never, never>>,
    '/reference/theme-config/layout': RouteRecordInfo<'/reference/theme-config/layout', '/reference/theme-config/layout', Record<never, never>, Record<never, never>>,
    '/reference/theme-config/nav': RouteRecordInfo<'/reference/theme-config/nav', '/reference/theme-config/nav', Record<never, never>, Record<never, never>>,
    '/reference/theme-config/sidebar': RouteRecordInfo<'/reference/theme-config/sidebar', '/reference/theme-config/sidebar', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
    '/tags copy/': RouteRecordInfo<'/tags copy/', '/tags copy', Record<never, never>, Record<never, never>>,
  }
}
